name: vacemedia_library
description: VaceMedia Library
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  agora_rtc_engine: 1.0.5
  permission_handler: ^5.0.1
  cloud_firestore: ^0.13.6
  firebase_auth: ^0.16.1
  firebase_messaging: ^6.0.16
  firebase_storage: ^3.1.6
  animations: ^1.1.0

flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
