name: vacemedia_library
description: VaceMedia Library
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  agora_rtc_engine: 1.0.5
  permission_handler: ^5.0.1+1
  cloud_firestore: ^0.13.7
  firebase_auth: ^0.16.1
  firebase_messaging: ^6.0.16
  firebase_storage: ^3.1.6
  animations: ^1.1.1
  shared_preferences: ^0.5.8
  path_provider: ^1.6.11
  material_design_icons_flutter: ^4.0.5345
  intl: ^0.16.1
  http: ^0.12.2
  page_transition: ^1.1.5
  uuid:

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
